---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
   chef_license: accept
verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
           - recipe[hellocookbook]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
